language: swift
osx_image: xcode11

branches:
  only:
    - master
    - develop

cache:
  directories:
    - Carthage

before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
  - carthage update --verbose --no-use-binaries --platform iOS --cache-builds

script:
  - xcodebuild clean build -project r2-lcp-swift.xcodeproj -scheme readium-lcp-swift -quiet
